[package]
name = "wexob"
version = "0.1.0"
authors = ["Exopteron", "Galaxtone"]
edition = "2018"
license = "GPL-3.0-or-later"
publish = false

[dependencies]
hyper = { version = "0.14", features = ["full"] }
tokio = { version = "1.8.0", features = ["full"] }